### ISSUE TITLE
HTTPS Check: Validate SSL not saving

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-app#101]
When checking the "Validate SSL" select box and hitting save, console throws errors and monitor is not updated:

![image](https://cloud.githubusercontent.com/assets/2886187/15227662/539014b6-1856-11e6-850e-b6b84690b4b2.png)

> Reported in https://raintank.groovehq.com/groove_client/mailboxes/33431/filters/196811/tickets/19078835

**Comment by woodsaj** [comment]
this is because this form element is using the editorCheckbox directive which only supports boolean values.  But we need to use strings, ie 'true' or 'false'
