### ISSUE TITLE
Cannot create more than 3 Endpoints

### ISSUE THREAD

**Issue by chirshan** [raintank/worldping-app#103]
I have the issue that, when I want to create an 4th Endpoint I get an Enexpected error:
![image](https://cloud.githubusercontent.com/assets/13982472/15395701/280e1dd2-1dd9-11e6-91f1-80ee036e03d5.png)

in the grafana log i get a 403 Forbidden:
![image](https://cloud.githubusercontent.com/assets/13982472/15395804/835413a4-1dd9-11e6-8ce6-6479481e9b88.png)

This Problem only occurs when I try to add a 4th Endpoint. When I delete one and create another one with a different domain, it works, but not with the 4th.

The Problem appers no matter if I'm using an admin oder editor API Key.

**Comment by woodsaj** [comment]
@chirshan as we are in Beta still, all orgs have a quota of 3 endpoints.  You can reach out to @mattttt on our slack channel to discuss increasing your quota.

But the errors message provided is horrible and issue exists for it already. https://github.com/raintank/worldping-app/issues/44
