### ISSUE TITLE
[Bug] Validate SSL Certificate checkbox submit code: 400

### ISSUE THREAD

**Issue by drewboswell** [raintank/worldping-app#107]
When editing an endpoint, under https check editing, if you tick/untick the "validate SSL certificate" and press update https settings you get:

(This happens even if you un-tick the box, as it still submits the deactivated element)

\########
error code 400
message: DeserializationError; json: cannot unmarshal bool into Go value of type string

\# **Version information**
Grafana-server: 3.0.2
Worldping version: 1.0.7
Server arch: Linux XEN x86_64 GNU/Linux

**Comment by Dieterbe** [comment]
duplicate of #101 we just need to roll this out ( most likely today)

**Comment by drewboswell** [comment]
Ah yes sorry I didn't see the other one for some reason, I confirm that it is the same problem.
