### ISSUE TITLE
[Bug] Saved probes on https check are updated only on edit panel

### ISSUE THREAD

**Issue by drewboswell** [raintank/worldping-app#108]
When editing endpoints, under the https check section, when you updated the probes and save:

###### On edit endpoint page
- Line: Monitoring from {option} {endpoint list (x and 11 more probes)} is correct
- Accordion title recap is false: Every 60s from 2 probes

###### On /page/endpoint-details
- last check from 2 probes --> leads me to believe that the changes are somehow not being taken into account everywhere

This appears to only be the case for the https check from what I've seen.

\# **Version information**
Grafana-server: 3.0.2
Worldping version: 1.0.7
Server arch: Linux XEN x86_64 GNU/Linux

**Comment by woodsaj** [comment]
this looks to be due to incorrect binding of the model to the endpoint-collector-select directive.

```
<endpoint-collector-select model="ctrl.monitors['http']" collectors="ctrl.collectors" style="modal-collector-select"></endpoint-collector-select>
```

This is also preventing users from updating the probe locations for https checks.
