### ISSUE TITLE
[Bug] wolrdping-endpoint-web protocol http, graphite render problem (code: 500)

### ISSUE THREAD

**Issue by drewboswell** [raintank/worldping-app#109]
The dashboard makes the following request:
\# **Request**
/api/plugin-proxy/raintank-worldping-app/api/graphite/render
\# **Referrer**
/dashboard/db/worldping-endpoint-web?var-protocol=https&var-endpoint=name&var-probe=All
\# **Params**
target: alias(averageSeries(litmus.name.{amsterdam,charleroi,chicago,frankfurt,london,los-angeles,miami,new-jersey,new-york,omaha,paris,portland,san-francisco,seattle,silicon-valley,singapore,south-carolina,sydney,taipei,tokyo}.http.dns), 'dns')
target: alias(averageSeries(litmus.name.{amsterdam,charleroi,chicago,frankfurt,london,los-angeles,miami,new-jersey,new-york,omaha,paris,portland,san-francisco,seattle,silicon-valley,singapore,south-carolina,sydney,taipei,tokyo}.http.connect), 'connect')
target:"alias(averageSeries(litmus.name.{amsterdam,charleroi,chicago,frankfurt,london,los-angeles,miami,new-jersey,new-york,omaha,paris,portland,san-francisco,seattle,silicon-valley,singapore,south-carolina,sydney,taipei,tokyo}.http.send), 'send')"
target:"alias(averageSeries(litmus.name.{amsterdam,charleroi,chicago,frankfurt,london,los-angeles,miami,new-jersey,new-york,omaha,paris,portland,san-francisco,seattle,silicon-valley,singapore,south-carolina,sydney,taipei,tokyo}.http.wait), 'wait')"
target:"alias(averageSeries(litmus.name.{amsterdam,charleroi,chicago,frankfurt,london,los-angeles,miami,new-jersey,new-york,omaha,paris,portland,san-francisco,seattle,silicon-valley,singapore,south-carolina,sydney,taipei,tokyo}.http.recv), 'recv')"
from:"-3h"
until:"-1min"
format:"json"
maxDataPoints:"20"

\# **Stack Trace Response**
`Traceback (most recent call last):
  File "/usr/share/python/graphite/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/share/python/graphite/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/share/python/graphite/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/python/graphite/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/python/graphite/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/python/graphite/site-packages/graphite_api/app.py", line 384, in render
    data_store = fetchData(context, paths)
  File "/usr/share/python/graphite/site-packages/graphite_api/render/datalib.py", line 160, in fetchData
    time_info, series = finder.fetch_multi(nodes, startTime, endTime)
  File "/usr/share/python/graphite/site-packages/graphite_raintank.py", line 219, in fetch_multi
    data = self.fetch_from_tank(nodes, start_time, end_time)
  File "/usr/share/python/graphite/site-packages/graphite_raintank.py", line 252, in fetch_from_tank
    raise Exception("metric-tank said: %s" % resp.text)
Exception: metric-tank said: <html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>`

\# **Version information**
Grafana-server: 3.0.2
Worldping version: 1.0.7
Server arch: Linux XEN x86_64 GNU/Linux

**Comment by woodsaj** [comment]
@dieterbe, that query looks normal. Any insight on what metrictank doesnt like about it?

**Comment by Dieterbe** [comment]
I think this is haproxy cause none of those strings occur in the MT or go source code
```
~/g/s/g/r/raintank-metric ❯❯❯ ack 'Your browser sent an invalid request'
~/g/s/g/r/raintank-metric ❯❯❯ ack '400 Bad request'
~/g/s/g/r/raintank-metric ❯❯❯ cd ~/code/go
~/c/go ❯❯❯ ack 'Your browser sent an invalid request'
~/c/go ❯❯❯ ack '400 Bad request'                                                                                                                                                             ⏎
~/c/go ❯❯❯    
```

**Comment by woodsaj** [comment]
HAPROXY will send a 400 "for an invalid or too large request".  So I think this is due to https://github.com/raintank/graphite-raintank/issues/19

**Comment by woodsaj** [comment]
@drewboswell the fix has been deployed to worldping-api.raintank.io.  Let us know if you still get errors.

**Comment by drewboswell** [comment]
Looking good! I can't reproduce the error now, so I would say that it's fixed.

Thanks for the reactivity.
