### ISSUE TITLE
can no longer use adminKey as apiKey, now triggers "invalid apiKey"

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-app#112]
we used to be able to use the adminKey as an apiKey when configuring WP. (e.g. changeme in the raintank-docker stack), but now this triggers "invalid apiKey" errors

**Comment by woodsaj** [comment]
this works fine for me, so there is no bug in the worldping-app.  Perhaps there is something wrong with your raintank-docker stack.
