### ISSUE TITLE
[Bug] Can't update any endpoint

### ISSUE THREAD

**Issue by grobie** [raintank/worldping-app#113]
I'm not able to update any endpoint in neither my local grafana setup (grafana 3.0.4, worldping 1.0.8) nor app.raintank.io. The field I need to update is `path` but it doesn't work with any other field either.

Org is "SoundCloud". I reported it to @mattttt some days ago and provided him with a CURL command. I can provide you with an updated curl command (including my auth token etc.), just ping me on slack.

**Comment by woodsaj** [comment]
this is a backend issue. moving this issue to raintank/worldping-api
