### ISSUE TITLE
Identify & Filter based on anycast site

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-app#127]
From a client: 
> I need a few features added that would make it able to replace other external transaction time
monitoring solutions, namely the ability to identify what anycasted site each
probe is connecting to, and be able to filter/tag data based on that.

**Comment by woodsaj** [comment]
certainly not possible until we have support for tags in the TSDB.  And even then the only way to be able to identify the anycasted site a request is served from is if the web servers include that information in a response header.  However as this is not a standard header adding support for this would be a customization specifically for this user and so doesnt make sense to implement.
