### ISSUE TITLE
bad units on web dashboard redux

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-app#128]
you may have noticed I like to complain about units not being applied correctly.
see also #84

looks like they are still not correct.

in the code at https://github.com/raintank/raintank-probe/blob/master/checks/http.go i see this:
```
	dataLength := float64(buf.Len())
(...)
		throughput := dataLength / (recv / 1000.0)
		result.Throughput = &throughput
```
this means dataLength is in bytes (good) and since `recv` is in ms, throughput is in *bytes* per second, not bits per second. in other words our throughput charts are off by a factor of 8.

**Comment by Dieterbe** [comment]
related: https://github.com/raintank/raintank-probe/pull/30

**Comment by woodsaj** [comment]
fix merged
