### ISSUE TITLE
[Feature Request] Provide reference data

### ISSUE THREAD

**Issue by grobie** [raintank/worldping-app#133]
We're currently monitoring google.com as a reference service to verify that any endpoint failures are not the result of general network issues of a probe. Assuming a similar need exists for other customers, it'd be great if worldping would provide such reference data for all customers, reducing the global number of checks a single probe needs to perform; and our costs ;)

**Comment by woodsaj** [comment]
@grobie we already provide reference data.  On any dashboard you can select the "~google_com_demo" endpoint which is public data available to all users.

**Comment by grobie** [comment]
You're right, my bad. I had misjudged it for an artifact of the endpoint we configured. I can't recall why we didn't have that data when we configured our reference endpoint, but it works without issues now.
