### ISSUE TITLE
stuff breaks when trying to enable worldping plugin in docker stack

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-app#135]
* run raintank-docker stack
* go to plugins -> worldping
* paste in a valid api key and hit the green button

3 things happen that shouldn't:

1)
a red error box appears with the message
```
<html> <head><title>500 Internal Server Error</title></head> <body bgcolor="white"> <center><h1>500 Internal Server Error</h1></center> <hr><center>nginx/1.9.14</center> </body> </html> 
```
in dev tools i see the request was to `http://localhost:3000/api/plugin-proxy/raintank-worldping-app/api/org/quotas` and the response was the same thing as what's in the error message.

2) I get a red message saying
```
Error
invlid apiKey
```

this is incorrect, and also there's a typo in there.

**Comment by Dieterbe** [comment]
note: nothing in the logs dir, and `docker logs e230a1e39fb6` just shows entries like
```
[Macaron] Completed /api/v2/probes 200 OK in 663.556µs
2016/08/26 08:41:52 [D] api.v2.probes.GET took 504.655µs.
[Macaron] Started GET /api/v2/probes for 172.19.0.1
2016/08/26 08:41:53 [D] api.v2.probes.GET took 471.502µs.
[Macaron] Completed /api/v2/probes 200 OK in 605.202µs
[Macaron] Started GET /api/v2/probes for 172.19.0.1
[Macaron] Completed /api/v2/probes 200 OK in 576.504µs
2016/08/26 08:41:54 [D] api.v2.probes.GET took 443.97µs.
[Macaron] Started GET /api/v2/probes for 172.19.0.1
[Macaron] Completed /api/v2/probes 200 OK in 597.035µs
2016/08/26 08:41:55 [D] api.v2.probes.GET took 475.91µs.
```

**Comment by woodsaj** [comment]
@Dieterbe if you are not seeing anything in the logs for worldping-api, then this is a problem with your raintank-docker environment, not a problem with the worldping-app.

The invlid typo was fixed two releases ago.  You should update your app.
