### ISSUE TITLE
Ability to see quota usage?

### ISSUE THREAD

**Issue by TryTryAgain** [raintank/worldping-app#141]
Is there currently a way to see quota usage? I think this would be very valuable information to have.

**Comment by mattttt** [comment]
@TryTryAgain Yes! In v1.1, to be released today/tomorrow, your Current Checks/mo will be available on the Config tab within your Grafana.

**Comment by TryTryAgain** [comment]
Fantastic! Guess I wasn't the only one who say benefit in having insight. Thanks for the reply, great work!
