### ISSUE TITLE
wP DNS: Dashboard failed to import

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-app#143]
When attempting to import the DNS dashboard into my local instance, the grafana dashboard importer (from dashboard tab in the plugin view) fails to import. But when I copy/paste the exact same JSON into the Import Dashboard modal, it works. 

I'm sure there is something super obviously wrong with this JSON (as it was working previously), but I have no idea what it is. I've run it through a linter and looked for errors. 

File: 
https://github.com/raintank/worldping-app/blob/one-dot-one/dist/dashboards/rt-endpoint-dns.json

Gif:
![dash-import](https://cloud.githubusercontent.com/assets/2886187/18729628/85337bd4-8020-11e6-8675-79a4c013891a.gif)

Need some help :(

**Comment by mattttt** [comment]
This is what the grafana server logs say:

```
EROR[09-21|17:32:16] Failed to import dashboard               logger=context userId=1 orgId=1 uname=admin error="Dashboard not found"
EROR[09-21|17:32:16] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/import status=500 remote_addr=[::1] time_ms=2ns size=40
```

And this is console:
![screenshot 2016-09-21 17 34 05](https://cloud.githubusercontent.com/assets/2886187/18729890/ae660f5c-8021-11e6-9e1b-3b01c44a073a.png)


And network:
![screenshot 2016-09-21 17 34 32](https://cloud.githubusercontent.com/assets/2886187/18729885/ab7b1936-8021-11e6-8d9b-0c7012405d62.png)

**Comment by mattttt** [comment]
I should also mention, it's definitely something in that JSON - because when I grab an earlier version and try and import it, everything works like a charm.

**Comment by woodsaj** [comment]
@mattttt you need to remove the "id" field from the json or set it to null

**Comment by mattttt** [comment]
Doh, thought I tried that. Will give it another shot, thanks!

**Comment by mattttt** [comment]
Fixed.
