### ISSUE TITLE
Raintank api-key without GUI?

### ISSUE THREAD

**Issue by Luke1887** [raintank/worldping-app#159]
Hi everybody,

is there a way to add the raintank api-key without the GUI?
Currently I am setting up a grafana server via puppet and install misc. plugins via exec.
I realy do not want to use the GUI, especially when testing to build a container in docker...

Kind regards
Luke

**Comment by woodsaj** [comment]
@Luke1887 yes it is possible, but you would need to do more than just add the key.  When you add the key the app verifies it then adds the necessary datasources and finally imports the dashboards.

All of these steps are performed via the grafana backend API, so you could automate them.

You should be able to use your browser's developer tools to inspect the requests made to the backend when configuring the app.
