### ISSUE TITLE
can not find worldping plugin

### ISSUE THREAD

**Issue by heipacker** [raintank/worldping-app#160]
when i install raintank-worldping-app successfully, and restart. but can not find worldping plugin, why?

**Comment by heipacker** [comment]
worldping version 1.1.0
grafana version 3.1.1

**Comment by woodsaj** [comment]
@heipacker have you enabled the plugin as described in the installation instructions?
https://grafana.net/plugins/raintank-worldping-app/installation

**Comment by heipacker** [comment]
has resolved, is permission denied problems. ths
