### ISSUE TITLE
Refactor Elastisearch.go to support 2.x

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-app#168]
Problem: As of Grafana 4.1.0 Beta, ElasticSearch 1.x is no longer supported.

worldPing currently is relying on ES 1.x so https://github.com/raintank/tsdb-gw/blob/master/elasticsearch/elasticsearch.go needs to be refactored to support the 2.x query payload.

Our ES cluster is running 2.2, so it would probably be better to accept the "format" field and pass it through to ES.

This is high priority, as anyone attempting to run worldPing on 4.1.0 Beta will have broken events.

**Comment by mattttt** [comment]
@woodsaj unsure what it'll take to address it, and appears to be busy on other more critical stuff. 

@DanCech volunteered to take a look, but if it turns into something bigger, suggest we enlist @daniellee's help. He is plugin master, his app-fu is strong.

**Comment by woodsaj** [comment]
This has been fixed in the tsdb-gw service and deployed to production.
