### ISSUE TITLE
support setting "body" for http/https checks

### ISSUE THREAD

**Issue by woodsaj** [raintank/worldping-app#172]
The backend supports a "body" field to be used when requests are made from the probes.

To use this capability, we just need to add a "textarea" form element for the body, perhaps conditionally showing the field for "PUT", "POST", "PATCH" and "DELETE".

**Comment by woodsaj** [comment]
We will probably also want to add a "content-type" selector that will automatically populate the "Headers" with the correct content.

**Comment by DanCech** [comment]
added textarea in 3ab69d09757164e0c06befe611cd20f6b6a4363a
content type selector adds complexity if we want to handle non-standard types, what happens if the user has entered one manually, etc.  Not sure if we want to go ahead with that?

**Comment by woodsaj** [comment]
yeah, lets just leave the content-type setting out for now.  users will just need to add it to the "headers" section themselves.
