### ISSUE TITLE
Charleroi misplaced on worldmap

### ISSUE THREAD

**Issue by pauvos** [raintank/worldping-app#174]
![screenshot from 2017-02-06 16-34-01](https://cloud.githubusercontent.com/assets/984187/22653653/618e74a0-ec8a-11e6-9d8c-a3ac325555e9.png)

I know it's the post-factual era but charleroi is still in belgium. :)

**Comment by woodsaj** [comment]
lat/long has been updated.

@pauvos thanks for reporting this, and sorry it took so long for us to resolve it.
