### ISSUE TITLE
Omaha misplaced on world map

### ISSUE THREAD

**Issue by erikgrinaker** [raintank/worldping-app#175]
Omaha is placed near San Jose:

<img width="610" alt="screen shot 2017-02-16 at 13 57 46" src="https://cloud.githubusercontent.com/assets/644420/23023970/fffd4eaa-f44f-11e6-9fc5-8d9b794d92c9.png">

**Comment by mattttt** [comment]
Thanks @erikgrinaker, will fix!

**Comment by daniellee** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/434655/23071311/28604c42-f52e-11e6-8d9d-ee1d3e41fad9.png)

**Comment by erikgrinaker** [comment]
Great, thanks @daniellee!
