### ISSUE TITLE
Any way to change the state notifications email address?

### ISSUE THREAD

**Issue by mikepruett3** [raintank/worldping-app#177]
We are using the WorldPing plugin on our locally hosted Grafana server, and we have our Grafana server configured to send from a specific email address. (to bypass Email AV, and Malware engines)

For some reason, the alerts from the WorldPing plugin are delivered from **hello@raintaink.io**. Is there anyway to change this, or configure the plugin to use our Internal Email server like Grafana is?

**Comment by woodsaj** [comment]
@mikepruett3 unfortunately not.

The worldping product is a SaaS platform that uses Grafana for the frontend.   So though your grafana server is running locally, all of the worldping backend, which collects and stores the metrics and generates the alerts, runs on our own infrastructure.
