### ISSUE TITLE
Display the Org being used when configuraing the app

### ISSUE THREAD

**Issue by woodsaj** [raintank/worldping-app#179]
a few customers have run into issues where they have used an ApiKey for their personal user/org instead of a company based org.

When the problem is discovered, users need to delete their endpoints and re-create new ones losing all of their previous data.

To help prevent this problem, we should prominently show the Org being used (based on the apiKey) during configuration.

**Comment by mattttt** [comment]
Current versions of wP have this in the config.

![screenshot 2017-03-13 17 31 54](https://cloud.githubusercontent.com/assets/2886187/23876275/0d272160-0813-11e7-848c-c70c07a30d39.png)


Are you thinking that it should be prominent across all app pages (add endpoint, endpoint config, etc)?

**Comment by woodsaj** [comment]
Yeah, forgot we had that.  I think it is enough.
