### ISSUE TITLE
worldPing Demo: Get it up to snuff

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-app#183]
We're talking about: https://worldping-demo.raintank.io/

- [x] Change URL to worldping-demo.grafana.com.
- [x] Update Grafana and the worldPing app (currently running Grafana version: 3.0.2 and 1.0.8 respectively).
- [x] Please set up monitoring, so we know if it's down.

We want to link this on Monday in NYC, so if you could tackle it early on your day on Monday, that would be very helpful.

**Comment by DanCech** [comment]
we could run this on worldping-demo.grafana.net

**Comment by woodsaj** [comment]
I provisioned a new server for this, as it was easier to start with a fresh install.
