### ISSUE TITLE
Alternate Approches for DatasourceUpgrader

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-app#186]
So in testing the new DatasourceUpgrader functionality, I've had unreliable results. 

Sometimes throwing errors and warnings, sometimes working just fine. The fear is that even after a successful upgrade, it's possible that a user could receive this error anytime in the future.

It also relies on the admin knowing to both run grafana-cli _and_ log into the front-end, as any other lesser credentialed user would not be able to update the datasource settings automatically. 

Is there a way to update the datasource as part of the grafana-cli upgrade instead of relying on the front-end?

**Comment by DanCech** [comment]
No.

**Comment by nopzor1200** [comment]
That's unfortunate @dcech. What can we do as part of an install/update other than re-import Dashboards, is that about it?

I'm just entering into this conversation, my understanding may be off. But it seems like a really bad idea to check datasources and try to update, on every single panel and dashboard load. 

I understand this may be the only way to provide a 'seamless' experience, but until we can provide this functionality in a better place, maybe we're better off requiring existing users to manually reconfigure their data sources.

**Comment by DanCech** [comment]
grafana-cli doesn't provide any capability to execute code, all it does is to download the plugin and unpack the files into the grafana directory.

**Comment by mattttt** [comment]
Thoughts from @torkelo on grafana-cli doing more: 
> Oh, really tricky. Needs a new plugin hook to run code on startup when plugin updated, but trickier than that as plugin is frontend only, hmm

And further investigation shows:

> @awoods: because it looks like there are some serious bugs in Grafana when switching orgs. I just created a new org on my local grafana, then enabled worldping with a new apiKey, then deleted the apiKey.  But when i switch from my main org, to this new org, my worldping-endpoint list page renders, even though it shouldnt. If i navigate away and back to the page it correctly gives me an auth error

> @awoods: The erorr you describe, where it tried to create a datasource that already existed, and the errors i am getting both seem to caused by the same problem. And that is that just after switching orgs, the first few requests to grafana continue using the old org.

> @DCech: yeah it's reliant on the active org being synchronized between the frontend and the api session. it seems like it should be relatively simple to add support in the grafana api mmiddleware for an X-Org-ID header or orgId= param. that way the frontend could explicitly specify the org for each api call

but....

**Comment by mattttt** [comment]
I think this approach is still fragile, and it seems unnecessary to check datasources constantly. 

Instead, I propose the following for discussion:

1. User upgrades worldPing via grafana-cli or one-click on Grafana.com
2. User goes to a worldping Dashboard. The CTA Panel & Nav panel have new functionality that check some new account variable about whether the datasource upgrade has occurred. 
3. If it has not been upgraded...
 a. We also store a new variable about notifications to trigger a notification within the CTA and Nav panel that says "You have a task to complete in the worldPing config". 
 b. The user clicks to go to the Plugin config. We show a notification message saying "In order to take advantage of this upgrade and use alerting, you need to click here and upgrade your Datasource (or, "find an admin to do this because you dont have privileges"
 c. We give immediate feedback saying "You're all set, thanks!" or "We've reached an error, please contact us for help at support@grafana.com" instead of just showing a red error bar on the upper right that goes away after 2 seconds. 
4. When it has been upgraded (after a successful step 3)
 a. The notification does not appear.

I know what you're thinking - notifications should be in Grafana, not built into apps themselves. I know, I agree, and we'll get there. But until that happens, perhaps this is a better mid-term solution to drive action items into new releases, isolating the data source checking to the least accessed page (config) and establishes a behavior to push new notifications to the user in the future.

Side benefit: This also allows us to see what clients have yet to update their data source and send out email reminders in the future.

**Comment by woodsaj** [comment]
Any variables to track the upgrade need to be stored inside of grafana on a per org basis as the same worldping account can be installed on multiple grafana orgs and or servers.  We cant track it in the worldping-api backend.

The solution you suggest does nothing to solve the current problems which are due to grafana bugs.  There is no work around to the grafana backend returning incorrect data when it is queried.

The current logic is extremely simple, what you suggest just makes the process more complicated.

1) user upgrades via grafana-cli
2) when a user visits any worldping page or uses any worldping panel:
    - if the user is not an admin, we do nothing
    - if the user is an admin, we check to see if an upgrade has been performed. This check is performed by making a single query to the grafana backend to get the list of known datasources.  If the required datasources are present and have the correct properties, then nothing further is needed. Otherwise we update the datasources.

**Comment by mattttt** [comment]
So, agreed that my solution is more complicated and doesnt even work because of multiple org/instances/etc. 

I also agree that the above solution is much simpler. However those Grafana bugs are going to cause some people to have a very bad worldPing experience for this release. 

People loading  a dashboard and getting unexpected "datasource not updated" errors that disappear after 2 seconds does not build confidence in our product - it erodes it, regardless of whether it was a Grafana or worldPing bug. 

The one important difference in the solution I proposed is that the user would click a button to initiate the action - which then gives context to the errors, if they appears. At least they know it's tied to something they just tried to do. Random errors after an upgrade are bad. 

What if we do the checks, as proposed, but show people a button to click in the CTA and nav panels?. Then if something goes wrong, we can show more verbose errors with a link to contact support, or they can try it again (in the case of a locking issue).

Im reaching for ideas - but I do not want to release a *simple* solution that can lead to a poor upgrade.

**Comment by woodsaj** [comment]
> cause some people to have a very bad worldPing experience for this release.

My understanding is that the problem only occurs when you navigate to a page within a few seconds of "Switching" orgs.  This problem is not limited to worldping,  lots of other components within Grafana are likely to generate errors as well.

With your proposal, instead of just getting a "datasource not updated" message users will instead get a notification that they need to go to the config page and upgrade, even though their datasources are already upgraded.

So am open to changes, but as i mentioned in my previous comment:

> There is no work around to the grafana backend returning incorrect data when it is queried.

**Comment by torkelo** [comment]
> The solution you suggest does nothing to solve the current problems which are due to grafana bugs. There is no work around to the grafana backend returning incorrect data when it is queried.

Any info on those bugs would be great. And how does this issue relate to switching orgs? Any details would be great, might be something I can fix. Trying to find any other reference to Grafana returning incorrect data here, is there another issue for that here or an old Grafana issue? 

> Any variables to track the upgrade need to be stored inside of grafana on a per org basis as the same worldping account can be installed on multiple grafana orgs and or servers. We can't track it in the worldping-api backend.

Any app can store settings (on per org basis). So that could be one solution. But as you stated in another comment just looking at the data source url would be enough. And looks to me the best solution. 

@mattttt 
> Sometimes throwing errors and warnings, sometimes working just fine. 

Is this what you mentioned in https://github.com/grafana/grafana/issues/7992  ? Fail to replace that here. The only way I can if I use a stress test tool and do write operations with high concurrency. The default sqlite3 database is not a good fit for that scenario and so far only one person that know of has encountered this (utkarsh when doing parallel imports of dashboards). What write operations is the worldping app doing concurrently?

**Comment by woodsaj** [comment]
@torkelo 

> What write operations is the worldping app doing concurrently?

https://github.com/raintank/worldping-app/blob/master/src/components/config/dsUpgrade.js#L65
we don't deliberately try to update both datasources concurrently, but we send both POST/PUT commands  at about the same time and then just wait for all of the promises to resolve.

While we could refactor to chain the promises to work around this problem, grafana not just blocking on one of the requests while the other updates the table seems like a bug to me.

**Comment by torkelo** [comment]
@woodsaj yea, agree. Managed to replicate it with 5 concurrent requests. I guess is depends on disk speed & latency as well. So if someone runs on a slow VM disk it might be easier to replicate. One possible fix that I just committed to grafana master is to limit max open connections to 1 (only when sqlite3 is used), this solved the issue and could not notice any performance degradation with some basic load testing. 

https://github.com/grafana/grafana/commit/95e0010a5be0cb1f3b7b43122a289b854ef648f6

**Comment by woodsaj** [comment]
Yeah, i have a lot of trouble replicating the issue. I just spent 30mins trying by moving my sqlite db to a SATA disk, then saturating the disk with read/writes using a disk benchmarking tool (iozone).  Even when the disk is at 100% utilization i still wasnt able to  trigger the issue in worldping-app.  So i suspect that there is something wrong with @mattttt's grafana installation or perhaps this is OSX issue.

**Comment by DanCech** [comment]
This was resolved.
