### ISSUE TITLE
map panel

### ISSUE THREAD

**Issue by woodsaj** [raintank/worldping-app#19]
<a href="https://github.com/nopzor1200"><img src="https://avatars.githubusercontent.com/u/9953157?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nopzor1200](https://github.com/nopzor1200)**
_Friday Apr 17, 2015 at 22:53 GMT_
_Originally opened as https://github.com/raintank/grafana/issues/20_

---

We need to create a map panel to support map functionality around Collectors, both in the Litmus pages as well as the Grafana Dashboards.

Ideally this can be accomplished as a stock Grafana panel, and can be used in an embedded manner in necessary Litmus pages.

Requirements of the map:
- Autowindow/autozoom based on the items selected (ie. smart enough to show the world for listing all collectors, but zooming into Europe for EMEA, down to showing New York metro for someone looking at a hypothetical "NYC" tag, etc etc)
- Be able to represent 1-5 values on each item in the map (either as a color shade, dots, etc etc), alongside annotations or notes
- Make sure its consistent with our look and feel
- Ideally not dependent on external accounts / costs

**Comment by woodsaj** [comment]
<a href="https://github.com/nopzor1200"><img src="https://avatars.githubusercontent.com/u/9953157?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nopzor1200](https://github.com/nopzor1200)**
_Friday Apr 17, 2015 at 22:55 GMT_

----

This has also been discussed within the Grafana community before:

https://github.com/grafana/grafana/issues/1088

https://github.com/grafana/grafana/issues/1520

**Comment by woodsaj** [comment]
<a href="https://github.com/nopzor1200"><img src="https://avatars.githubusercontent.com/u/9953157?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nopzor1200](https://github.com/nopzor1200)**
_Sunday Apr 26, 2015 at 17:09 GMT_

----

Perhaps in the interim we should change the map graphic in Collectors List to indicate where our default public Collectors are. Thoughts?

**Comment by woodsaj** [comment]
<a href="https://github.com/bulletfactory"><img src="https://avatars.githubusercontent.com/u/1950595?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bulletfactory](https://github.com/bulletfactory)**
_Sunday Apr 26, 2015 at 17:11 GMT_

----

I like that- a static graphic until we get the live map solution worked out.

T

**Comment by woodsaj** [comment]
<a href="https://github.com/nopzor1200"><img src="https://avatars.githubusercontent.com/u/9953157?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nopzor1200](https://github.com/nopzor1200)**
_Tuesday Apr 28, 2015 at 22:02 GMT_

----

Static map committed

**Comment by woodsaj** [comment]
<a href="https://github.com/torkelo"><img src="https://avatars.githubusercontent.com/u/10999?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [torkelo](https://github.com/torkelo)**
_Monday May 11, 2015 at 11:01 GMT_

----

I can't really give an ETA on this, I would expect this to take a couple of days at least or more than a week. And my feeling is that there are more important things to work on.

**Comment by woodsaj** [comment]
<a href="https://github.com/mattttt"><img src="https://avatars.githubusercontent.com/u/2886187?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattttt](https://github.com/mattttt)**
_Monday May 18, 2015 at 22:09 GMT_

----

Some updates since we chatted:
Torkel did some testing in codepen with: http://codepen.io/awilbert/pen/wAGLp

Also, here's an explainer that we had kicked around internally on how the stack fits together:
http://www.sarasafavi.com/making-a-web-map-with-leaflet.html

**Comment by woodsaj** [comment]
<a href="https://github.com/nopzor1200"><img src="https://avatars.githubusercontent.com/u/9953157?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nopzor1200](https://github.com/nopzor1200)**
_Tuesday Jun 23, 2015 at 16:51 GMT_

----

Still would be a big win for certain components.

**Comment by woodsaj** [comment]
<a href="https://github.com/nopzor1200"><img src="https://avatars.githubusercontent.com/u/9953157?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nopzor1200](https://github.com/nopzor1200)**
_Saturday Nov 21, 2015 at 01:33 GMT_

----

Just pinging on here because I want to talk about this and get a strategy together. I still feel this is something that's important to drive Litmus adoption.

I think that it gets more interesting with the Elasticsearch datasource, too.

**Comment by woodsaj** [comment]
a map panel now exists.  Rather then pushing a new version of the app, the plan is to just publish a new dashboard to grafana.net which uses the map panel.

first panel should be a map that shows probes that are in an error state.
Need template variables for <endpoint|all>, <protocol|all>

panel then should get litmus.$endpoint.*.$proto.error_state => aliasByNode(2)

**Comment by mattttt** [comment]
This is built and staged in the next version of wP. Assigning to me to follow through and release.
