### ISSUE TITLE
WorldPing to monitor local devices/services?

### ISSUE THREAD

**Issue by dxm765** [raintank/worldping-app#198]
I was wondering if there was any plan to be able to utilize WorldPing to monitor internal services , even if its just pinging the IP and/or port from the Grafana host and returning a up/down/timeout status.

**Comment by woodsaj** [comment]
@dxm765 you can do this by simply deploying a private probe on your internal network.  You can then configure endpoints to run checks on the private probe the connect to your internal network.  
When adding an endpoint for an internal service, the endpoint discovery phase will fail, but you can then just configure the checks manually.
