### ISSUE TITLE
"Sydney" public probe cannot be used

### ISSUE THREAD

**Issue by terrabakky** [raintank/worldping-app#204]
When configured to use the Sydney probe no data is returned and the probe isn't visible.

![image](https://user-images.githubusercontent.com/1826837/30045169-d83446e6-9245-11e7-9af9-9dbeaf5580b0.png)

![image](https://user-images.githubusercontent.com/1826837/30045129-90e6d132-9245-11e7-9ada-214981ee490b.png)

**Comment by woodsaj** [comment]
This probe was experiencing issues, specifically, it was not creating new checks when they were configured.  THe probe has been restarted and is running normally again.
