### ISSUE TITLE
404 errors on loading js scripts in worldping plugin

### ISSUE THREAD

**Issue by bonobo78** [raintank/worldping-app#208]
Hi folks :grinning:,

I've been looking around a solution to solve my problem but can't find something relevant.

We are publishing grafana behind HAPROXY reverse-proxy.
Everything works fine except 3 js scripts from **worldping plugin**.

~~I've tried without reverse-proxy it works well.~~ In fact, it's the same behaviour with or without reverse-proxy
For now the only working version tested is : 4.4.3

Edit :
* running on Windows
* Grafana 4.6.3
* worldPing-app 1.2.3

Any idea why only these 3 js scripts can't be downloaded ?

errors from grafana app :

     Plugin Error
     Fetch error: 404 Not Found Instantiating http://my.domain.local/public/plugins/filters/all.js Loading http://my.domain.local/public/plugins/raintank-worldping-app/panels\endpoint-list/module.js Loading plugins/raintank-worldping-app/panels\endpoint-list/module
     Plugin Error
     Fetch error: 404 Not Found Instantiating http://my.domain.local/public/plugins/components/config/dsUpgrade.js Loading http://my.domain.local/public/plugins/raintank-worldping-app/panels\call-to-action/module.js Loading plugins/raintank-worldping-app/panels\call-to-action/module

errors in server log file : 

     t=2018-01-16T20:47:18+0100 lvl=info msg="Request Completed" logger=context userId=5 orgId=1 uname=myuser method=GET path=/public/plugins/components/config/dsUpgrade.js status=404 remote_addr=172.x.x.x time_ms=15 size=25935 referer="http://my.domain.local/dashboard/db/worldping-home?orgId=1"
     t=2018-01-16T20:47:18+0100 lvl=info msg="Request Completed" logger=context userId=5 orgId=1 uname=myuser method=GET path=/public/plugins/directives/all.js status=404 remote_addr=172.x.x.x time_ms=15 size=25935 referer="http://my.domain.local/dashboard/db/worldping-home?orgId=1"
     t=2018-01-16T20:47:18+0100 lvl=info msg="Request Completed" logger=context userId=5 orgId=1 uname=myuser method=GET path=/public/plugins/filters/all.js status=404 remote_addr=172.x.x.x time_ms=0 size=25935 referer="http://my.domain.local/dashboard/db/worldping-home?orgId=1"

And the server custom configuration file : 

    [server]
    protocol = http
    http_port = 34101
    domain = "my.domain.local"
    enforce_domain = true
    root_url = %(protocol)s://%(domain)s/
    router_logging = false

**Comment by woodsaj** [comment]
@bonobo78 what version of Grafana are you using?
Are you using the latest version of worldping-app?
Did you install the app as per the instructions at https://grafana.com/plugins/raintank-worldping-app/installation ?

**Comment by bonobo78** [comment]
Sorry. I forgot these important informations! 
Yes I use latest versions. 
Installation was made by following these instructions.

**Comment by woodsaj** [comment]
@bonobo78  what version of Grafana?   Latest stable version (4.6.3)? or current master

**Comment by bonobo78** [comment]
Latest stable. 
Grafana 4.6.3 
worldPing-app 1.2.3

**Comment by bonobo78** [comment]
> I've tried without reverse-proxy it works well.
In fact this test was made with version 4.4.3

I'm trying to push this version behind the reverse-proxy.

**Comment by bonobo78** [comment]
Just tried grafana 4.4.3 and it works like a charm.
I've made a try with 4.6.2 : the problem is already present.
Something probably went wrong between 4.4.3 and 4.6.2

I'll try to upgrade version by version to found out when the regression was introduced.

**Comment by bonobo78** [comment]
Found answer on Grafana community : https://github.com/grafana/grafana/issues/9541

Thanks for your time.
