### ISSUE TITLE
[Feature Request] Add PagerDuty integration

### ISSUE THREAD

**Issue by d-shi** [raintank/worldping-app#214]
In addition to email alerts, it would be great to have the same PagerDuty integration that Grafana alerting already supports, so incidents can be resolved automatically once the probes are healthy again.

**Comment by woodsaj** [comment]
@d-shi   You can already integrate with PagerDuty using a Pagerduty "email" integration.

- create a new or select an existing PagerDuty service
- add a new integration of type "Email"
- Edit the integration
  - under "email management" select "Open and resolve incidents based on custom rules:"   then set 2 rules.

rule1:
- **Resolve** an incident if **all** of the following conditions apply
- The email subject **contains**: is OK
- Link incoming emails to the same incident if they share this key: 
   in the email **subject**, match **all text before**:  " is "    
  (dont include the quotes, but keep the space before/after the word is)

rule 2:
- **Trigger** an incident if **all** of the following conditions apply
- The email subject **does not contain**: is OK
- Link incoming emails to the same incident if they share this key: 
   in the email **subject**, match **all text before**:  " is "    
  (dont include the quotes, but keep the space before/after the word is)


You can then use the `integration email` address as the email in your worldping endpoint configs.
