### ISSUE TITLE
raintankEvents Data Source and error 404

### ISSUE THREAD

**Issue by jostrasser** [raintank/worldping-app#217]
Hi,
is it normal that the "raintankEvents" Data Source gets an error 404 after clicking Save&Test?

I cannot an configuration mistake on my side and If I try to browse the url "https://tsdb-gw.raintank.io/elasticsearch/" I also get an "404 not found"

![image](https://user-images.githubusercontent.com/14274103/54044965-975d7c00-41d0-11e9-8901-ef471e365de0.png)

Thanks JO!

**Comment by tsnow20** [comment]
I'm seeing the same thing here. Perhaps the raintankEvents URL has changed? I haven't been able to find any documentation as to what the URL should be now.

**Comment by alex-berger** [comment]
Same here, I guess the base URL is still fine, but it returns 404 if the HTTP method or path is not appropirate (see https://github.com/raintank/worldping-api/blob/master/pkg/api/elasticsearch.go).

```
curl -v https://tsdb-gw.raintank.io/elasticsearch/_stats 
< HTTP/2 401 
< server: nginx/1.15.10
< date: Mon, 12 Aug 2019 06:04:37 GMT
< content-type: application/json; charset=UTF-8
< content-length: 14
< strict-transport-security: max-age=15724800
< 
"Unauthorized"%  
```
From the fact, that WorldPing seems to work correctly despite those 404 errors in the UI, I assume that this is just a side effect of a [locked down](https://github.com/raintank/worldping-api/blob/master/pkg/api/elasticsearch.go) elasticsearch data source. The (generic) Grafana UI expects a fully (non locked down) elasticsearch data source and therefore produces those 404 errors.

Any feedback/clarifications from the maintainers @woodsaj?

**Comment by woodsaj** [comment]
@alex-berger 's assumption is right.  Elasticsearch is used in the backend for storing the event data, but requests from users pass through an application layer that restricts the queries that can be sent.     
Grafana used to use the `_stats` query to test the datasource, and this used to work.  However, Grafana now uses a query to `_mapping` and this is not currently supported.

Though the "test" in the datasource editor in Grafana returns an error, it wont have any impact on worldping-app working.


The configuration shown in @jostrasser original post is the correct configuration.  

If users think that the datasource settings are incorrect, you can just delete the datasource, then go to the worldping "Plugin Config" page in your grafana (https://<your grafana host>/plugins/raintank-worldping-app/)  and click "update".  The the app will then automatically re-create the datasource.
