### ISSUE TITLE
Summary Dashboard not display data

### ISSUE THREAD

**Issue by chiauho** [raintank/worldping-app#247]
Hi,
I setup Worldping to check DNS & ping. My summary dashboard shows no data. However the dashboards "worldPing Endpoint: |--- DNS" & "worldPing Endpoint: |--- Ping" are displaying data ok. What am I missing?

Thanks for helping.

ch

**Comment by electron0zero** [comment]
Hi @chiauho 👋🏼,

worldPing will reach End-Of-Life (EOL) on April 1, 2021

Everything you love about worldPing is now available with the new synthetic monitoring feature in Grafana Cloud, plus you’ll get reduced complexity and all the benefits of Grafana Cloud. 

Take the first step to get started with synthetic monitoring by signing up for a Grafana Cloud account. [Get started for free.](https://go2.grafana.com/worldPing-EOL-grafana-cloud.html?pg=plugins-wp&plcmt=body-txt)

**Comment by chiauho** [comment]
Thank you Sarah for informing me.

Regards
