### ISSUE TITLE
Endpoint List- Dashboard Panel

### ISSUE THREAD

**Issue by woodsaj** [raintank/worldping-app#48]
<a href="https://github.com/mattttt"><img src="https://avatars.githubusercontent.com/u/2886187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mattttt](https://github.com/mattttt)**
_Tuesday Sep 29, 2015 at 22:39 GMT_
_Originally opened as https://github.com/raintank/grafana/issues/477_

----

stub, but to get this working:

![screenshot_2015-09-18_08 40 36](https://cloud.githubusercontent.com/assets/2886187/10180233/6d0054bc-66d9-11e5-9fdb-9d827888a1b1.png)

**Comment by woodsaj** [comment]
<a href="https://github.com/mattttt"><img src="https://avatars.githubusercontent.com/u/2886187?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattttt](https://github.com/mattttt)**
_Tuesday Sep 29, 2015 at 22:40 GMT_

----

Started in: https://github.com/raintank/grafana/tree/endpoint-list-panel

**Comment by woodsaj** [comment]
<a href="https://github.com/mattttt"><img src="https://avatars.githubusercontent.com/u/2886187?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattttt](https://github.com/mattttt)**
_Friday Nov 06, 2015 at 23:42 GMT_

----

This is complete and in production. Next is to add the filters.

**Comment by woodsaj** [comment]
<a href="https://github.com/nopzor1200"><img src="https://avatars.githubusercontent.com/u/9953157?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nopzor1200](https://github.com/nopzor1200)**
_Saturday Nov 21, 2015 at 01:19 GMT_

----

Nice job on getting this refactored as a panel btw. I think the biggest use case is in the "Home dashboard" for the Litmus plugin. I think its important to remember that doing this opens up showing "time related" stuff on the panel!

**Comment by woodsaj** [comment]
<a href="https://github.com/nopzor1200"><img src="https://avatars.githubusercontent.com/u/9953157?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nopzor1200](https://github.com/nopzor1200)**
_Saturday Nov 21, 2015 at 01:20 GMT_

----

And should look at whether the panel should respect endpoint arguments, eg. all, or a specific one.

**Comment by mattttt** [comment]
This has been released for a long time.
