### ISSUE TITLE
Color Override on Admin Account

### ISSUE THREAD

**Issue by woodsaj** [raintank/worldping-app#52]
<a href="https://github.com/mattttt"><img src="https://avatars.githubusercontent.com/u/2886187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mattttt](https://github.com/mattttt)**
_Thursday Nov 05, 2015 at 21:37 GMT_
_Originally opened as https://github.com/raintank/grafana/issues/520_

----

There have been a few times where I've caught myself almost making changes on a client's organization as I bounce between open tabs. With that, do you suppose we can put some kind of check in there that says:

If logged in UserID = 1 AND OrgID != 1, then:

![screenshot 2015-11-05 16 34 40](https://cloud.githubusercontent.com/assets/2886187/10982466/5788df54-83db-11e5-9a26-0f35e37add6e.png)

This is just a quick and dirty mockup, we'll make it look better. Anyone else see the value in this?

**Comment by woodsaj** [comment]
<a href="https://github.com/nopzor1200"><img src="https://avatars.githubusercontent.com/u/9953157?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nopzor1200](https://github.com/nopzor1200)**
_Friday Nov 20, 2015 at 20:51 GMT_

----

Maybe a settable badge or background color per Org would be the best way to accomplish this across Grafana and raintank.

 It solves this problem and allows for some visual customization/distinction on a per-Org basis that would be useful to people for all sorts of reasons (branding, distinguishing, etc)

Otherwise might have to introduce raintank-specific functionality since a lot of small Grafana users might only have 1 user (admin). Switching admin to a "abnormal" icon implies that we want to discourage that behavior?

**Comment by woodsaj** [comment]
<a href="https://github.com/bulletfactory"><img src="https://avatars.githubusercontent.com/u/1950595?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bulletfactory](https://github.com/bulletfactory)**
_Friday Nov 20, 2015 at 21:09 GMT_

----

Do we think leveraging/using the avatar for users and orgs which already exist in the sidebar would be too subtle to notice?

**Comment by woodsaj** [comment]
<a href="https://github.com/woodsaj"><img src="https://avatars.githubusercontent.com/u/8415072?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [woodsaj](https://github.com/woodsaj)**
_Monday Nov 23, 2015 at 06:53 GMT_

----

how is logging in as the Grafana Admin, with the "admin" role on may different Orgs different to logging in as any other user with the "admin" role on may different orgs?  Is the problem not the same for all users.

Sounds to me that the problem is simply that the "current Org" is not prominent enough in the UI.

**Comment by mattttt** [comment]
closing this, not relevant anymore with current wP setup.
