### ISSUE TITLE
Info required

### ISSUE THREAD

**Issue by Himanshu-pupneja** [raintank/worldping-app#56]
Hi,

I installed plugin "raintank-worldping-app" into grafana.
But the datasource in not configured automatically.

even the configure button is not working, attached the snapshot.

![image](https://cloud.githubusercontent.com/assets/15123322/14273855/4534550a-fb2b-11e5-916b-6dcd104bec02.png)

can you share the steps to do the same?

Rehards,
Himanshu

**Comment by woodsaj** [comment]
@Himanshu-pupneja  the datasource is automatically created when you enter your ApiKey and enable the app.

The screen you have provided looks to be the result of you clicking the "reset" buttons to clear the apiKey and datasource state.

**Comment by Himanshu-pupneja** [comment]
Thanks @woodsaj ,
I generated new API and its working fine now.

This can be closed
