### ISSUE TITLE
provide immediate feedback when entered api key is invalid

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-app#61]
see #58

**Comment by Himanshu-pupneja** [comment]
+1
#56 
it was not working on the first API that i generated.
but in second attempt it was working.

Not sure its a bug or something else.

**Comment by Dieterbe** [comment]
@Himanshu-pupneja interesting. i had a similar problem. in firefox on linux the first key it generated i copy pasted with the "copy to clipboard" feature on the site, and it didn't work. but the one after i copy pasted manually and it did. but everyone else in the team is not having issues, so not sure where the problem lies.
how did you do it? which browser & os? did you use the "copy to clipboard" feature for the first try? for the second? were the permission roles the same? (should be admin or it doesn't work. so i used admin both times)

**Comment by DanCech** [comment]
The first key in Himanshu's account was an Editor key which is why it didn't work.  The second working key is an Admin key.

**Comment by DanCech** [comment]
Correction: The assumption that Editor keys wouldn't work was incorrect, Editor keys should work just fine.

@Himanshu-pupneja if you still have the "Main Org." token that didn't work could you paste it here?  I see that it's been deleted in the database so there isn't any issue with sharing it.

**Comment by woodsaj** [comment]
If you see this problem again, set the log level in Grafana to "Debug".  It will then log the headers added to plugin-proxy requests (ie requests the worldping-app makes to the worldping-api backend).  These headers will include the Authentication header that has the key.

You can then verify that this key was correctly stored.

It is not easy to just pull the key out of the DB as it is encrypted before being stored.

**Comment by Himanshu-pupneja** [comment]
@Dieterbe, 
Grafana is installed on RHEL6.5 and i was using Chrome through Windows. I copy and pasted API to plugin and Enable it. In second attempt i got the pop kind off message that raintank data source added(I dont remember exactly the message) but it didn't come up on the first attempt.

@DanCech,
Yes that was the only difference, first key was editor and second was Admin.
Unfortunately i don't have the first key, i deleted that when the second attempt was successful.

**Comment by Dieterbe** [comment]
thanks @woodsaj !
