### ISSUE TITLE
no more litmus in welcome email plz kthx

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-app#74]
observed on QA:
![welcome-to-litmus-wut](https://cloud.githubusercontent.com/assets/20774/14624728/3f3fcc08-05ab-11e6-9698-4ec3c4827350.png)

**Comment by mattttt** [comment]
Argh, I did a full directory search for litmus in the email directory. Not sure how I could have missed it. Good eye @dieter, thanks! 

On the upside, the only people that would have seen this is existing orgs inviting co-workers, which has been a low number.

**Comment by mattttt** [comment]
Fixed in PR https://github.com/raintank/worldping-api/pull/40

Push out pls, @ctdk

**Comment by mattttt** [comment]
Closing assuming the @ctdk did this.
