### ISSUE TITLE
Address on the same zone are not resolving

### ISSUE THREAD

**Issue by wmbzz** [raintank/worldping-app#75]
Hi guys.
Yesterday I updated Grafana to 3.0, installed the Zabbix plugin to re-enable the data source and went to install worldPing, which I am very excited about. The first endpoint that I created is working perfectly, but now any other page on the same zone as the first one (we have several publications within the same zone, *.promaxcloud.com.br) won't work. This is the one that it's working:
![untitled](https://cloud.githubusercontent.com/assets/6979278/14638555/19b18d4c-060e-11e6-8094-df039bf6f7a7.png)

When I try another one on the same zone the discovery proccess doesn't find anything (all of this publications are on the same datacenter as well, btw):

![untitled](https://cloud.githubusercontent.com/assets/6979278/14638611/68eeca6e-060e-11e6-9833-318101f14c97.png)
The address for this one is http://brapira.promaxcloud.com.br, but we have 10 more.

Thanks in advance.

**Comment by wmbzz** [comment]
Checking grafana log I get:
2016/04/19 10:12:33 [I] Completed REDACTED admin "GET /api/endpoints/discover HTTP/1.1" 504 Gateway Timeout 182 bytes in 60254986us

But I'm sure the publication is online.

**Comment by woodsaj** [comment]
@wmbzz the error you are getting is because brapira.promaxcloud.com.br does not respond ICMP pings or to http requests on port 80 (http) or port 443 (https).  I have tested this from our production servers and also from my personal desktop. All get the same result.

Due to the host not responding the entire discovery process is failing.

**Comment by wmbzz** [comment]
Yeah, feeling a bit stupid now. I forgot we have a dedicated link with the hosting service, and the client's IP has a firewall rule to allow the connection. Thanks for your time.
