### ISSUE TITLE
Add new Endpoint - Intermittently not loading

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-app#78]
Customer reported an issue that I've seen repeatedly, but have yet to report it because I thought it might have been unique to my dev setup (and I wanted to better research before reporting). Now that someone else is seeing it, is worth mentioning:

> Oh, and there is a small bug report - sometimes when I press "Add new Endpoint", the page is not loaded (it is blank with the top bar loaded only, "Add a new endpoint" heading and content is not loaded), so I have to refresh it. I am using Firefox 45.0 on Ubuntu. (https://app.raintank.io/plugins/raintank-worldping-app/page/endpoint-config)

A refresh always fixes it for me, and I havent been able to track down how to replicate it consistently.

**Comment by woodsaj** [comment]
@mattttt not much i can do unless i can replicate this. If you see the problem again can you share any errors reported in the browser console.

**Comment by mattttt** [comment]
![gif-of-screen](https://cloud.githubusercontent.com/assets/2886187/14825132/a1a3b750-0ba6-11e6-99d8-d0d59b3883cd.gif)
