### ISSUE TITLE
"dashboard not found" errors

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-app#79]
when i'm on a summary dash like
https://dev-portal.raintank.io/dashboard/db/worldping-endpoint-summary?var-probe=All&var-endpoint=dieter_plaetinck_be
and i click any link like ping or http, it takes me to:
https://dev-portal.raintank.io/dashboard/file/rt-endpoint-ping.json?from=now-3h&to=now&var-endpoint=dieter_plaetinck_be&var-probe=All
https://dev-portal.raintank.io/dashboard/file/rt-endpoint-web.json?from=now-3h&to=now&var-endpoint=dieter_plaetinck_be&var-probe=All&var-protocol=https
and results in "dashboard not found" errors

**Comment by mattttt** [comment]
@Dieterbe Verified this is not happening in master. It's been fixed and tested for quite a while. Also, looking at the grafana version, my guess is that this is just running a hella old version of wP. 

My guess is that we lost our super cool automation to keep dev up to date somehow :(

**Comment by Dieterbe** [comment]
we determined this was due to dashboards not updating (wheras WP itself was updating fine) on dev.
for now we should manually reimport dashboards.
