### ISSUE TITLE
"update settings" buttons faulty layout

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-app#81]
seen on dev-portal in firefox on linux. in chrome it looks good.

![a](https://cloud.githubusercontent.com/assets/20774/14801803/3eb1bb2e-0b1a-11e6-8cd7-07a3d23ee5a5.png)
![b](https://cloud.githubusercontent.com/assets/20774/14801804/3eb36b4a-0b1a-11e6-8b5f-f97a1c9e7b9a.png)
![3](https://cloud.githubusercontent.com/assets/20774/14801805/3eb4f56e-0b1a-11e6-9e86-f1c1508cd91b.png)

**Comment by mattttt** [comment]
This is a known issue that deals with responsiveness. Will get this nailed down with the new form styles.

**Comment by mattttt** [comment]
Fixed in 1.0.7
