### ISSUE TITLE
Proxy Question

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-app#86]
From Groove Ticket 192

>Thank you about the interest. Well I'm trying the beta version of grafana 3 on a testing environment and I wasn' t able to connect because my test server is behind a proxy. Is there an application setting for http/s proxy?

Can someone help me answer this for them?

**Comment by woodsaj** [comment]
Proxy settings need to be passed to the grafana-server binary via environment variables.

see https://github.com/grafana/grafana/issues/1691

**Comment by mattttt** [comment]
Thanks! Customer has been notified. Closing.
