### ISSUE TITLE
Plugin should work on grafana-server behind firewall with no internet access

### ISSUE THREAD

**Issue by drewboswell** [raintank/worldping-app#99]
The plugin makes plugin-proxy calls via the server, which is not compatible with companies that have a no Internet access policy on production setups. 

We do not want to open access to our network zone that contains our production grafana/graphite/ELK/InfluxDB setup.

Perhaps the use of a license file, or making the calls directly via the browser would be a solution? This is in any case a problem for us, and be a major blocker for adoption for others I imagine.

Example calls the server is trying to make:
/api/plugin-proxy/raintank-worldping-app/api/endpoints
/api/plugin-proxy/raintank-worldping-app/api/org/quotas

**Comment by torkelo** [comment]
since worldping is an external service (metrics are stored in the raintank hosted metrics database) external internet access is required from your grafana-server.

**Comment by drewboswell** [comment]
I understand that given that it is external it needs internet, I am just wondering if it could be configured like the datasources for elasticsearch or graphite are: proxy/direct. I see that the datasource for raintank has the "direct/proxy" setting but it still passes via the server in any case.

**Comment by woodsaj** [comment]
The Worldping service is a SaaS service, so to use it you will need internet access to be able to use it.

@drewboswell unfortunately it is not possible for the the api requests to the worldping backend to be made directly from the browser.  The api requests need to be authenticated with an apiKey and would be very insecure to expose this key to the browser.  So instead this apiKey is stored (encrypted) in the Grafana database and added to requests when they are being proxied.

You do no not need to have direct Internet access on the Grafana server, you can instead just use a HTTP/HTTPS proxy.  To have Grafana use the proxy, you need to pass the proxy addresses via **http_proxy** and **https_proxy** environment variables.

**Comment by drewboswell** [comment]
Very true about it being insecure with that method, sounds logical to me.

It might be a good idea to add to the documentation/requirements that an http(s) proxy for direct ( grafana-server --> SaaS ) access is needed.

**Comment by drewboswell** [comment]
For the proxy setup I have a few questions:

- Is the following URL pattern enough for opening on a proxy? **https://app.raintank.io/***
- What verb/methods need to be authorized? GET/POST/DELETE etc?

**Comment by woodsaj** [comment]
All of the routes needed are listed in the app's plugin.json

https://github.com/raintank/worldping-app/blob/master/plugin.json#L6-L47

So in summary, you need GET/PUT/POST/DELETE on https://worldping-api.raintank.io/api/*

The routes may change in future as we add new features, so when updating the app it would pay to check the plugin.json for an changes.

**Comment by drewboswell** [comment]
setting http_proxy/https_proxy settings does not seem to work.

The proxy is well configured as I can wget/curl to https://worldping-api.raintank.io/api/*. However the datasource uses "access:direct" passing via the "api/plugin-proxy/raintank-worldping-app/api/*", and I get the impression it is not sending the requests through the proxy at all.

I get the following in the logs:
2016/05/19 17:25:35 [T] Adding header to proxy request. Authorization: Bearer {secret}
2016/05/19 17:25:35 [I] setting key Authorization value Bearer {secret}
2016/05/19 17:26:05 [I] Completed {local-IP} {user} "GET /api/graphite/metrics/find HTTP/1.1" 500 Internal Server Error 0 bytes in 30306811us

When using a proxy what do I need to have as a datasource configuration? (direct/proxy, url, credentials etc).

**Comment by drewboswell** [comment]
Perfect this works for me now thank you.

http_proxy=protocol://ip:port/
https_proxy=protocol://ip:port/
no_proxy=127.0.0.0/8,domain.com,etc

this works properly when added to a wrapper start script for grafana.
